### ISSUE TITLE
Bug ? Secret door spotting

### ISSUE THREAD

**Issue by uniwars** [Saibot393/perceptive#64]
Hi, I'm testing the invisible spotting feature and tried some things with a secret door and found out that :

![image](https://github.com/Saibot393/perceptive/assets/65986545/0fcac83f-ac51-4b17-b0b2-04a6911511e2)

The spotting range doesn't seem to work, token can spot the door with no range limit

The token respot the door at each movement (if the door is already spot it shouldn't respot it I think, and it has failed the passive check once it shouldn't give another chance for each square moved I guess)

The "spotted by" section is not filled with the name of the actor who has spot the door.

I'm using Foundry v11 315, last module version and Pf2e 5.12.3

**Comment by Saibot393** [comment]
I think i have identified the problem. What is your world setting "Apply ranges" set to? Should it be set to never that would explain the behaviour and the behaviour would almost be expected (except for the spamming the found message again and again part)

**Comment by Saibot393** [comment]
The bug should now be fixed with v3.1.14, assuming the above to be true. I will leave it open for now in case my assumption was wrong

**Comment by uniwars** [comment]
Yeah I missed this setting, sorry, the range works fine now.

I made the update and found out some new things :

![image](https://github.com/Saibot393/perceptive/assets/65986545/0e014ef7-ce0b-4fd1-b5da-f8c5178fd748)
The message was not sent when the token spotted the door and the actor is not mentionned in the "spotted by" section

For each movement the door is "refreshed" for the token making it flashes (only when it has been spotted with passive perception, active perception works fine)
I guess the passive eprception it no rolled for each movement if it failed once, at least I tried to move a lot in a passive DC that I didn't pass the first time and never get it passed.

Is it intended that a spotted door is only visible within the spotting range even when already spotted ? The token who knows where the door is may be able to remember where it is even when leaving the spotting range (maybe as a setting ?)

**Comment by Saibot393** [comment]
Only tokens that have actively spotted a door are mentioned in the "Spotted by" section

The token refresh is a visual bug based on the way foundry renders the scene, i have not yet found a way to prevent it.

The door only being visible within the passive range, even when spotted actively is currently a limitation of the implementation, there is a way i could decouple it but that would come at somewhat of a performance hit. I am currently considering a way to rewrite it without costing performance but that will take a bit of time.

**Comment by uniwars** [comment]
I remember arms reach I believe having the same issue with door flashing but I couldn't find back my issue at the time to see if it could help you.

For the spotted by, is that on purpose ? Is the button to reset spotted by supposed to hide the door again for everyone who spotted it ? Because when I tried it with a door spotted by passive the token could still see it so for ym tests I needed to delete and recreate a door

**Comment by Saibot393** [comment]
The "reset spotted by" button should make the door invisible to all tokens that have spotted the door via active rolls (assuming they can't spot the door via passive perception)

**Comment by uniwars** [comment]
The door was passively spotted so I guess it's normal then, but that would be cool if both worked with passive spotting too

the passive perception is the main feature for me because it saves a lot of time in comparison with needing to place monk's active tile everywhere

so if that's not an issue but a feature request I guess this issue is completed, thanks for the quick fix

**Comment by Saibot393** [comment]
I was planning on improving the spotting for doors in a similar way anway, so i will add that to it. May take a week or two though

**Comment by Saibot393** [comment]
Secret doors will no longer become normal doors when clicked whille being spotted with v3.2.0 (unless the appropiate setting is activated)
